language: node_js
node_js:
  - "4.4.1"

before_install:
  - git config --global push.default matching
  - git config --global user.name "gitforhzc"
  - git config --global user.email "clannadhzc@hotmail.com" 

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GH_TOKEN@github.com/gitforhzc/gitforhzc.github.io.git master

branches:
  only:
    - hexo
cache:
  directories:
    - node_modules
